In [6]:
msg="hellowworld"
print(msg)
a=3
b=4
c=a+b
print("a:{} b:{} c:{}".format(a,b,c))
import numpy as np
a=np.eye(4)
print (a)


hellowworld
a:3 b:4 c:7
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
